# Generated by Django 4.2.14 on 2024-07-10 22:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='skills/')),
                ('order', models.IntegerField(default=1)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='personalinfo',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='volunteering',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='workexperience',
            options={'ordering': ['-start_date']},
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='medium',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
