# Generated by Django 4.2.14 on 2024-07-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_skill_delete_skills_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='skills/'),
        ),
    ]
