# Generated by Django 4.2.14 on 2024-07-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_service_description_alter_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='sub_title',
            field=models.CharField(default='Hello', max_length=255),
            preserve_default=False,
        ),
    ]
