# Generated by Django 4.2.14 on 2024-07-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_personalinfo_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='meta_keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='meta_og_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='meta_og_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='meta_og_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='meta_twitter_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='meta_twitter_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='meta_twitter_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
